### ISSUE TITLE
Helm Chart Fails to Deploy ssi-dim-wallet-stub Due to Missing managed-identity-wallet:0.0.1 Image

### ISSUE THREAD

**Issue by CDiezRodriguez** [eclipse-tractusx/ssi-dim-wallet-stub#19]
## Describe the bug

The Helm Chart doesn't deploy the Wallet Stub. When I execute the Helm command, the Minikube dashboard shows the error: `manifest for tractusx/managed-identity-wallet:0.0.1 not found`. 

### To Reproduce

_Steps to reproduce the behavior:_

1. Run
```bash
helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
helm repo update
kubectl create namespace wallet
helm install ssi-dim-wallet-stub tractusx-dev/ssi-dim-wallet-stub
```

### Expected behavior

The `ssi-dim-wallet-stub` pod should be running in Kubernetes.

### Screenshots/Error Messages

![image](https://github.com/user-attachments/assets/c3354380-5f30-4b66-a3f8-221b758acc96)

## Context Informations

_Add any other context about the probleme here._

- Kubernetes version: v1.30.0
- Helm version: v3.16.1

## Possible Implementation

The deployment works locally when the image is replaced with the locally generated one. A possible solution is to upload the `ssi-dim-wallet-stub` image to the TractusX repository and set it as the default image, instead of `managed-identity-wallet`.

**Comment by nitin-vavdiya** [comment]
Thanks for reporting.

We already have a docker image on dockerhub: https://hub.docker.com/r/tractusx/ssi-dim-wallet-stub/tags

Values are wrong in the values.yaml file.  I will push it with the correct values

**Comment by mgarciaLKS** [comment]
Hello everyone.

The Deployment regarding this issue failed due to the chart version not changed, ¿can you fix it?

Thanks beforehand.

**Comment by nitin-vavdiya** [comment]
Issue fixed

Please try to install it with the below command:

```
helm repo update
helm install ssi-dim-wallet-stub tractusx-dev/ssi-dim-wallet-stub --version 0.1.1
```
