### ISSUE TITLE
Resource Not Appearing in Repo

### ISSUE THREAD

**Issue by CDiezRodriguez** [eclipse-tractusx/ssi-dim-wallet-stub#7]
## Describe the bug

When attempting to install the `ssi-dim-wallet-stub` directly from the Helm chart repository, the response indicates that the chart does not exist.

### To Reproduce

1. Add the Helm repository:
```bash
helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
```
2. Attempt to install the `ssi-dim-wallet-stub` Helm chart:
```bash
helm install ssi-dim-wallet-stub tractusx-dev/ssi-dim-wallet-stub
```
3. The following error message appears:
```bash
Error: INSTALLATION FAILED: chart "ssi-dim-wallet-stub" matching  not found in tractusx-dev index. (try 'helm repo update'): no chart name found
```
4. Update the Helm repository:
```bash
helm repo update
```
5.  Search for the expected Helm Chart:
```bash
helm search repo tractusx-dev
```

### Expected Behavior
The Helm chart for ssi-dim-wallet-stub should be successfully found and installed without errors.

### Actual Behavior
The installation fails, and Helm reports that the chart does not exist in the repository.

### Screenshots/Error Messages

![Captura desde 2024-09-11 10-37-28](https://github.com/user-attachments/assets/d1c7ef34-d9c0-4a2f-84f5-436eebcd70b4)

## Context Informations

- Helm version: v3.15.4

**Comment by nitin-vavdiya** [comment]
Thanks for rising this issue.
Helm chart is not pushed yet to tractusx-dev repository.
